export const NATIONALITIES = {
  AU: 'AU',
  BR: 'BR',
  CA: 'CA',
  CH: 'CH',
  DE: 'DE',
  DK: 'DK',
  ES: 'ES',
  FI: 'FI',
  FR: 'FR',
  GB: 'GB',
  IE: 'IE',
  IR: 'IR',
  NO: 'NO',
  NL: 'NL',
  NZ: 'NZ',
  TR: 'TR',
  US: 'US',
};

export const NATIONALITIES_NUMAN_NAME = {
  [NATIONALITIES.AU]: 'Australian',
  [NATIONALITIES.BR]: 'Brazilian',
  [NATIONALITIES.CA]: 'Canadian',
  [NATIONALITIES.CH]: 'Chinese',
  [NATIONALITIES.DE]: 'German',
  [NATIONALITIES.DK]: 'Danish',
  [NATIONALITIES.ES]: 'Spanish',
  [NATIONALITIES.FI]: 'Finnish',
  [NATIONALITIES.FR]: 'French',
  [NATIONALITIES.GB]: 'British',
  [NATIONALITIES.IE]: 'Irish',
  [NATIONALITIES.IR]: 'Iranian',
  [NATIONALITIES.NO]: 'Norwegian',
  [NATIONALITIES.NL]: 'Dutch',
  [NATIONALITIES.NZ]: 'New Zeland',
  [NATIONALITIES.TR]: 'Turkish',
  [NATIONALITIES.US]: 'American',
};

export const NATIONALITIES_COLOR = {
  [NATIONALITIES.AU]: 'gold',
  [NATIONALITIES.BR]: 'green',
  [NATIONALITIES.CA]: 'red',
  [NATIONALITIES.CH]: 'red',
  [NATIONALITIES.DE]: 'red',
  [NATIONALITIES.DK]: 'red',
  [NATIONALITIES.ES]: 'gold',
  [NATIONALITIES.FI]: 'blue',
  [NATIONALITIES.FR]: 'blue',
  [NATIONALITIES.GB]: 'red',
  [NATIONALITIES.IE]: 'green',
  [NATIONALITIES.IR]: 'green',
  [NATIONALITIES.NO]: 'red',
  [NATIONALITIES.NL]: 'orange',
  [NATIONALITIES.NZ]: 'darkBlue',
  [NATIONALITIES.TR]: 'red',
  [NATIONALITIES.US]: 'red',
};
